"""Real-Yomitan render harness.

The claim this module has to support is narrow but strict: geometry and
behaviour assertions must be measured in the *actual* Yomitan renderer, not in
a hand-written approximation of it. So the harness

* serves the unmodified pinned Yomitan `ext/` tree over HTTP, because
  `structured-content-generator.js` is an ES module with relative imports and
  the extension stylesheets pull in fonts and further CSS by absolute path;
* overlays one harness page into that tree so `/js/...` and `/css/...` resolve
  to real extension sources;
* drives it with Chromium via Playwright and calls Yomitan's own
  `StructuredContentGenerator.createStructuredContent`.

Nothing about the card is reimplemented here. Every class name, design token,
theme rule, and `details`/`summary` behaviour under test comes from the pinned
checkout, so a Yomitan-side rendering change shows up as a test failure rather
than as a silently stale local copy.
"""

from __future__ import annotations

import contextlib
import functools
import http.server
import os
import socketserver
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator

from .contract import OVERFLOW_TOLERANCE_PX

#: Pinned Yomitan checkout the harness renders against. Overridable so CI can
#: point at its own clone, but the version is asserted, never assumed.
YOMITAN_ROOT = Path(
    os.environ.get("BUGD_YOMITAN_ROOT", "/home/skerraut/work/bench-ref-yomitan")
).resolve()

#: The schema/extension revision this dictionary is built and validated against.
#: A mismatch means the harness is measuring a different renderer than the one
#: `make validate` pinned, so it is a hard failure rather than a warning.
EXPECTED_YOMITAN_VERSION = "26.8.24.0"

HARNESS_PAGE = Path(__file__).with_name("page.html")

#: Viewports under test. Yomitan's default popup is 400x250 CSS px; the narrow
#: value is the width a phone-sized or user-shrunk popup actually gets.
DESKTOP_VIEWPORT = {"width": 600, "height": 900}
NARROW_VIEWPORT = {"width": 320, "height": 900}


class _Handler(http.server.SimpleHTTPRequestHandler):
    """Static handler serving the Yomitan ext tree with the harness overlaid."""

    def translate_path(self, path: str) -> str:
        clean = path.split("?", 1)[0].split("#", 1)[0]
        if clean in ("/", "/index.html", "/harness.html"):
            return str(HARNESS_PAGE)
        return super().translate_path(path)

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002
        return  # keep pytest output readable


class _Server(socketserver.ThreadingTCPServer):
    daemon_threads = True
    allow_reuse_address = True


@contextlib.contextmanager
def serve_yomitan() -> Iterator[str]:
    """Serve the pinned Yomitan `ext/` tree; yield its base URL."""
    ext = YOMITAN_ROOT / "ext"
    if not (ext / "js" / "display" / "structured-content-generator.js").is_file():
        raise RuntimeError(
            f"pinned Yomitan checkout not found at {YOMITAN_ROOT}; "
            "set BUGD_YOMITAN_ROOT to a Yomitan clone"
        )
    handler = functools.partial(_Handler, directory=str(ext))
    with _Server(("127.0.0.1", 0), handler) as httpd:
        thread = threading.Thread(target=httpd.serve_forever, daemon=True)
        thread.start()
        try:
            yield f"http://127.0.0.1:{httpd.server_address[1]}/harness.html"
        finally:
            httpd.shutdown()
            thread.join(timeout=5)


def yomitan_revision() -> dict[str, str]:
    """Identify the pinned checkout the harness is actually rendering.

    `ext/manifest.json` is deliberately *not* used: it is generated by Yomitan's
    own dev tooling from `dev/data/manifest-variants.json`, which carries a
    `$YOMITAN_VERSION` placeholder, so a source checkout reports `0.0.0.0` and
    would silently pass any version check. `git describe` against the real
    commit is the only trustworthy identity.
    """
    import subprocess

    def git(*args: str) -> str:
        return subprocess.run(
            ["git", "-C", str(YOMITAN_ROOT), *args],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()

    return {
        "describe": git("describe", "--tags"),
        "commit": git("rev-parse", "HEAD"),
        # Empty when the checkout has no uncommitted changes to tracked files.
        "dirty": git("status", "--porcelain", "--untracked-files=no"),
    }


@dataclass(frozen=True)
class Box:
    """A rendered element's border box, in CSS pixels."""

    x: float
    y: float
    width: float
    height: float

    @property
    def right(self) -> float:
        return self.x + self.width

    @property
    def bottom(self) -> float:
        return self.y + self.height

    def overlaps(self, other: "Box") -> bool:
        return (
            self.x < other.right
            and other.x < self.right
            and self.y < other.bottom
            and other.y < self.bottom
        )


class RenderedCard:
    """One card rendered by real Yomitan, queried by CSS selector."""

    def __init__(self, page: Any) -> None:
        self._page = page

    # -- structure -------------------------------------------------------

    def count(self, selector: str) -> int:
        return self._page.locator(selector).count()

    def text(self, selector: str) -> str:
        return self._page.locator(selector).first.inner_text()

    def texts(self, selector: str) -> list[str]:
        return self._page.locator(selector).all_inner_texts()

    def attribute(self, selector: str, name: str) -> str | None:
        return self._page.locator(selector).first.get_attribute(name)

    def exists(self, selector: str) -> bool:
        return self.count(selector) > 0

    def html(self) -> str:
        return self._page.locator("#glossary-host").inner_html()

    # -- geometry --------------------------------------------------------

    def box(self, selector: str, index: int = 0) -> Box:
        handle = self._page.locator(selector).nth(index)
        box = handle.bounding_box()
        if box is None:
            raise AssertionError(f"selector is not rendered (no box): {selector!r}")
        return Box(box["x"], box["y"], box["width"], box["height"])

    def boxes(self, selector: str) -> list[Box]:
        return [self.box(selector, i) for i in range(self.count(selector))]

    def is_visible(self, selector: str) -> bool:
        return self._page.locator(selector).first.is_visible()

    def frame_box(self) -> Box:
        return self.box("#harness-frame")

    def overflows_frame(self, selector: str) -> list[Box]:
        """Boxes of `selector` that extend past the popup's right edge."""
        frame = self.frame_box()
        # Sub-pixel layout rounding is not an overflow defect.
        return [b for b in self.boxes(selector) if b.right > frame.right + 0.5]

    def computed(self, selector: str, prop: str) -> str:
        return self._page.locator(selector).first.evaluate(
            "(el, prop) => getComputedStyle(el).getPropertyValue(prop)", prop
        )

    def overflow_report(self) -> list[dict[str, Any]]:
        """Every card descendant whose box extends past the popup's right edge.

        Reported for the *whole card* in one pass rather than per selector,
        because an overflow defect is usually one unbreakable leaf inflating
        every ancestor: a per-selector check names the symptom, this names the
        cause. Each row carries the role, the two widths, and the wrapping
        properties that decide whether the content *can* wrap, so a failure
        message is directly actionable.

        Zero-size boxes are skipped: `ruby` collapses to 0x0 when every child is
        an `rt`, which is a furigana-source question, not a layout overflow.
        """
        return self._page.evaluate(
            """(tolerance) => {
                const frame = document.querySelector('#harness-frame')
                    .getBoundingClientRect();
                const root = document.querySelector('[data-sc-grammar-card]');
                const rows = [];
                for (const el of [root, ...root.querySelectorAll('*')]) {
                    const box = el.getBoundingClientRect();
                    if (box.width === 0 && box.height === 0) { continue; }
                    if (box.right <= frame.right + tolerance) { continue; }
                    const style = getComputedStyle(el);
                    rows.push({
                        tag: el.tagName.toLowerCase(),
                        role: Object.keys(el.dataset).join(',') || '(none)',
                        text: (el.textContent || '').trim().slice(0, 60),
                        width: +box.width.toFixed(1),
                        right: +box.right.toFixed(1),
                        frameRight: +frame.right.toFixed(1),
                        overhang: +(box.right - frame.right).toFixed(1),
                        elementChildren: el.children.length,
                        overflowWrap: style.overflowWrap,
                        wordBreak: style.wordBreak,
                        whiteSpace: style.whiteSpace,
                    });
                }
                return rows;
            }""",
            OVERFLOW_TOLERANCE_PX,
        )

    @staticmethod
    def describe_overflow(rows: list[dict[str, Any]]) -> str:
        """Render an overflow report as an actionable failure message."""
        if not rows:
            return "no overflow"
        # Leaves are the cause; ancestors merely inherit the overhang.
        leaves = [row for row in rows if row["elementChildren"] == 0] or rows
        lines = [f"{len(rows)} box(es) past the popup edge; causes:"]
        for row in leaves[:6]:
            lines.append(
                f"  {row['tag']}[{row['role']}] width={row['width']}px "
                f"right={row['right']}px > frame {row['frameRight']}px "
                f"(overhang {row['overhang']}px, "
                f"overflow-wrap:{row['overflowWrap']} "
                f"word-break:{row['wordBreak']} "
                f"white-space:{row['whiteSpace']}) {row['text']!r}"
            )
        return "\n".join(lines)

    # -- behaviour -------------------------------------------------------

    def open_details(self, selector: str = "details") -> None:
        self._page.locator(selector).first.evaluate("el => el.open = true")

    def open_all_details(self) -> int:
        """Open every disclosure; returns how many were opened."""
        return self._page.evaluate(
            """() => {
                const all = document.querySelectorAll('details');
                for (const el of all) { el.open = true; }
                return all.length;
            }"""
        )

    def details_open_states(self) -> list[bool]:
        return self._page.locator("details").evaluate_all("els => els.map(e => e.open)")

    def click(self, selector: str, index: int = 0) -> None:
        self._page.locator(selector).nth(index).click()

    def focus_order(self, limit: int = 40) -> list[dict[str, Any]]:
        """Tab through the card, recording what receives focus.

        Reports the live `document.activeElement` after each Tab press, so a
        disclosure that is unreachable by keyboard simply never appears.
        """
        self._page.locator("body").evaluate("el => el.focus()")
        self._page.evaluate("() => { document.activeElement?.blur(); }")
        seen: list[dict[str, Any]] = []
        for _ in range(limit):
            self._page.keyboard.press("Tab")
            info = self._page.evaluate(
                """() => {
                    const el = document.activeElement;
                    if (!el || el === document.body) { return null; }
                    const rect = el.getBoundingClientRect();
                    return {
                        tag: el.tagName.toLowerCase(),
                        cls: el.className || '',
                        text: (el.textContent || '').trim().slice(0, 60),
                        width: rect.width,
                        height: rect.height,
                    };
                }"""
            )
            if info is None:
                break
            if seen and info == seen[-1]:
                break
            seen.append(info)
        return seen

    def press(self, key: str) -> None:
        self._page.keyboard.press(key)

    def focus_ring(self, selector: str) -> dict[str, Any]:
        """Whether the element shows a visible focus indicator once focused.

        Keyboard reachability is not the whole requirement: WCAG 2.4.7 needs the
        focused control to be *visible*. `:focus-visible` styling only applies on
        a real keyboard interaction, so this focuses via Tab-equivalent scripted
        focus and then reads what the browser resolved.
        """
        return self._page.locator(selector).first.evaluate(
            """(el) => {
                el.focus();
                const style = getComputedStyle(el);
                return {
                    matchesFocusVisible: el.matches(':focus-visible'),
                    isActiveElement: document.activeElement === el,
                    outlineStyle: style.outlineStyle,
                    outlineWidth: style.outlineWidth,
                    outlineColor: style.outlineColor,
                    boxShadow: style.boxShadow,
                };
            }"""
        )

    def screenshot(self, path: str | Path) -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        self._page.locator("#harness-frame").screenshot(path=str(target))
        return target


class YomitanRenderer:
    """Renders structured content through the pinned real Yomitan generator."""

    def __init__(self, page: Any, url: str) -> None:
        self._page = page
        self._url = url

    def render(
        self,
        content: Any,
        *,
        styles_css: str = "",
        dictionary: str = "Bee's Ultimate Grammar Dictionary",
        viewport: dict[str, int] | None = None,
        theme: str = "light",
        os_scheme: str | None = None,
        forced_colors: bool = False,
        reduced_motion: bool = False,
        font_size: int | None = None,
    ) -> RenderedCard:
        """Render one card in the real generator under a specific environment.

        `theme` is Yomitan's own setting, applied as the `data-theme` attribute
        the extension sets on `:root` -- that is what `ext/css/display.css` and
        `ext/css/material.css` key their dark palette off.

        `os_scheme` is the *separate* `prefers-color-scheme` media state. It
        defaults to matching `theme`, which is the common case, but the two are
        genuinely independent: a user can run Yomitan's dark theme on a
        light-mode OS. Keeping them separable is deliberate, because a card
        stylesheet that reacts only to the media query renders light-mode text
        colours on Yomitan's dark background, and a harness that always moves
        both together can never observe it.
        """
        page = self._page
        page.set_viewport_size(viewport or DESKTOP_VIEWPORT)
        scheme = theme if os_scheme is None else os_scheme
        page.emulate_media(
            color_scheme="dark" if scheme == "dark" else "light",
            forced_colors="active" if forced_colors else "none",
            reduced_motion="reduce" if reduced_motion else "no-preference",
        )
        page.goto(self._url, wait_until="load")
        page.wait_for_function("() => window.__harnessReady === true")
        page.evaluate(
            "theme => { document.documentElement.dataset.theme = theme; }", theme
        )
        page.evaluate(
            """size => {
                if (size !== null) {
                    document.documentElement.style.fontSize = `${size}px`;
                }
            }""",
            font_size,
        )
        # Render first: `applyDictionaryStyles` scopes the sheet to the
        # dictionary title, and the attribute it targets is set during render.
        page.evaluate(
            "args => window.renderCard(args.content, args.dictionary)",
            {"content": content, "dictionary": dictionary},
        )
        if styles_css:
            page.evaluate(
                "args => window.applyDictionaryStyles(args.css, args.dictionary)",
                {"css": styles_css, "dictionary": dictionary},
            )
        return RenderedCard(page)

    def scoped_css(self) -> str:
        """The dictionary CSS as Yomitan actually installed it, after scoping."""
        return self._page.evaluate("() => window.__scopedCss")


__all__ = [
    "Box",
    "DESKTOP_VIEWPORT",
    "EXPECTED_YOMITAN_VERSION",
    "NARROW_VIEWPORT",
    "RenderedCard",
    "YOMITAN_ROOT",
    "YomitanRenderer",
    "serve_yomitan",
    "yomitan_revision",
]
